### ISSUE TITLE
ml-collections breaks on Python 3.12 by relying on removed `imp` module

### ISSUE THREAD

**Issue by hylkedonker** [google/ml_collections#30]
**Describe the bug**
This package no longer works on Python 3.12, because it relies on the `imp` module [which has been removed in Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html#imp).

**To Reproduce**
```python
from ml_collections import config_flags
```
which gives the error message:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/.local/lib/python3.12/site-packages/ml_collections/config_flags/__init__.py", line 17, in <module>
>     from .config_flags import DEFINE_config_dataclass
>   File "/home/user/.local/lib/python3.12/site-packages/ml_collections/config_flags/config_flags.py", line 23, in <module>
>     import imp
> ModuleNotFoundError: No module named 'imp'

**Environment:**
 - OS Version: Ubuntu 24.04 LTS
 - Python: 3.12

**Comment by hylkedonker** [comment]
I just came across this PR, which aims to fix the problem:
https://github.com/google/ml_collections/pull/28

**Comment by hylkedonker** [comment]
A duplicate of #24.
