### ISSUE TITLE
requirements.txt missing from PyPI source tarball

### ISSUE THREAD

**Issue by boegel** [google/ml_collections#7]
**Describe the bug**

The `requirements.txt` file is missing from the source tarball that was pushed to PyPI (see https://pypi.org/project/ml-collections/0.1.0/#files). That means installing from that source tarball is broken, because the `setup.py` tries to read `requirements.txt`, which leads to:

```
    Running setup.py (path:/tmp/eb-hdz3kwtm/pip-req-build-7djg6soh/setup.py) egg_info for package from file:///tmp/ml_collections/ml_collections-0.1.0
    Created temporary directory: /tmp/eb-hdz3kwtm/pip-pip-egg-info-s7iw7xqe
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/eb-hdz3kwtm/pip-req-build-7djg6soh/setup.py", line 42, in <module>
        install_requires=_parse_requirements('requirements.txt'),
      File "/tmp/eb-hdz3kwtm/pip-req-build-7djg6soh/setup.py", line 23, in _parse_requirements
        with open(requirements_txt_path) as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**To Reproduce**

* download `ml_collections-0.1.0.tar.gz` from https://pypi.org/project/ml-collections/0.1.0/#files
* unpack, and try to install with `pip install .`

***ConfigDict***

*(none, irrelevant)*

***ConfigFlags***

*(none, irrelevant)*

**Expected behavior**

Installing from PyPI source tarball works.

**Environment:**
 - OS: Linux
 - OS Version: RHEL8
 - Python: Python 3.8.6

**Additional context**

*(none)*

**Comment by boegel** [comment]
Same goes for `requirements-test.txt`, which is also required by `setup.py`: https://github.com/google/ml_collections/blob/7f749a281c69f9d0b339c05ecb94b80d95029f25/setup.py#L42-L43
